//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace var2
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersSet
    {
        public int Id { get; set; }
        public int IdClient { get; set; }
        public int IdAutopart { get; set; }
        public int IdManager { get; set; }
    
        public virtual AutopartsSet AutopartsSet { get; set; }
        public virtual ClientsSet ClientsSet { get; set; }
        public virtual ManagerSet ManagerSet { get; set; }
    }
}
