//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace var2
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuppliersSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SuppliersSet()
        {
            this.AutopartsSet = new HashSet<AutopartsSet>();
        }
    
        public int Id { get; set; }
        public string NameSupplier { get; set; }
        public string INN { get; set; }
        public string Address { get; set; }
        public string Telephone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutopartsSet> AutopartsSet { get; set; }
    }
}
